# Generated by Django 5.1.1 on 2024-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="average_prices",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("City", models.CharField(max_length=32)),
                ("Average_Price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="beijin",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=32)),
                ("average_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="guangzhou",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=32)),
                ("average_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="shanghai",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=32)),
                ("average_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="shenzhen",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=32)),
                ("average_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="taiyuan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=32)),
                ("average_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("min_price", models.IntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
    ]
